#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanVeXe
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyBanVeXe")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBanVe(BanVe instance);
    partial void UpdateBanVe(BanVe instance);
    partial void DeleteBanVe(BanVe instance);
    partial void InsertChiTietTuyen(ChiTietTuyen instance);
    partial void UpdateChiTietTuyen(ChiTietTuyen instance);
    partial void DeleteChiTietTuyen(ChiTietTuyen instance);
    partial void InsertChuyenXe(ChuyenXe instance);
    partial void UpdateChuyenXe(ChuyenXe instance);
    partial void DeleteChuyenXe(ChuyenXe instance);
    partial void InsertLoaiNguoiDung(LoaiNguoiDung instance);
    partial void UpdateLoaiNguoiDung(LoaiNguoiDung instance);
    partial void DeleteLoaiNguoiDung(LoaiNguoiDung instance);
    partial void InsertNguoiDung(NguoiDung instance);
    partial void UpdateNguoiDung(NguoiDung instance);
    partial void DeleteNguoiDung(NguoiDung instance);
    partial void InsertThoiDiem(ThoiDiem instance);
    partial void UpdateThoiDiem(ThoiDiem instance);
    partial void DeleteThoiDiem(ThoiDiem instance);
    partial void InsertTuyenXe(TuyenXe instance);
    partial void UpdateTuyenXe(TuyenXe instance);
    partial void DeleteTuyenXe(TuyenXe instance);
    partial void InsertXe(Xe instance);
    partial void UpdateXe(Xe instance);
    partial void DeleteXe(Xe instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::QuanLyBanVeXe.Properties.Settings.Default.QuanLyBanVeXeConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BanVe> BanVes
		{
			get
			{
				return this.GetTable<BanVe>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietTuyen> ChiTietTuyens
		{
			get
			{
				return this.GetTable<ChiTietTuyen>();
			}
		}
		
		public System.Data.Linq.Table<ChuyenXe> ChuyenXes
		{
			get
			{
				return this.GetTable<ChuyenXe>();
			}
		}
		
		public System.Data.Linq.Table<LoaiNguoiDung> LoaiNguoiDungs
		{
			get
			{
				return this.GetTable<LoaiNguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDung> NguoiDungs
		{
			get
			{
				return this.GetTable<NguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<ThoiDiem> ThoiDiems
		{
			get
			{
				return this.GetTable<ThoiDiem>();
			}
		}
		
		public System.Data.Linq.Table<TuyenXe> TuyenXes
		{
			get
			{
				return this.GetTable<TuyenXe>();
			}
		}
		
		public System.Data.Linq.Table<Xe> Xes
		{
			get
			{
				return this.GetTable<Xe>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BanVe")]
	public partial class BanVe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdVe;
		
		private string _IdChuyen;
		
		private string _TenHanhKhach;
		
		private string _SDTHanhKhach;
		
		private System.Nullable<int> _SoLuongMua;
		
		private System.Nullable<int> _GiaVe;
		
		private System.Nullable<int> _ThanhTien;
		
		private EntityRef<ChuyenXe> _ChuyenXe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdVeChanging(string value);
    partial void OnIdVeChanged();
    partial void OnIdChuyenChanging(string value);
    partial void OnIdChuyenChanged();
    partial void OnTenHanhKhachChanging(string value);
    partial void OnTenHanhKhachChanged();
    partial void OnSDTHanhKhachChanging(string value);
    partial void OnSDTHanhKhachChanged();
    partial void OnSoLuongMuaChanging(System.Nullable<int> value);
    partial void OnSoLuongMuaChanged();
    partial void OnGiaVeChanging(System.Nullable<int> value);
    partial void OnGiaVeChanged();
    partial void OnThanhTienChanging(System.Nullable<int> value);
    partial void OnThanhTienChanged();
    #endregion
		
		public BanVe()
		{
			this._ChuyenXe = default(EntityRef<ChuyenXe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVe", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdVe
		{
			get
			{
				return this._IdVe;
			}
			set
			{
				if ((this._IdVe != value))
				{
					this.OnIdVeChanging(value);
					this.SendPropertyChanging();
					this._IdVe = value;
					this.SendPropertyChanged("IdVe");
					this.OnIdVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdChuyen", DbType="VarChar(30)")]
		public string IdChuyen
		{
			get
			{
				return this._IdChuyen;
			}
			set
			{
				if ((this._IdChuyen != value))
				{
					if (this._ChuyenXe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdChuyenChanging(value);
					this.SendPropertyChanging();
					this._IdChuyen = value;
					this.SendPropertyChanged("IdChuyen");
					this.OnIdChuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHanhKhach", DbType="NVarChar(30)")]
		public string TenHanhKhach
		{
			get
			{
				return this._TenHanhKhach;
			}
			set
			{
				if ((this._TenHanhKhach != value))
				{
					this.OnTenHanhKhachChanging(value);
					this.SendPropertyChanging();
					this._TenHanhKhach = value;
					this.SendPropertyChanged("TenHanhKhach");
					this.OnTenHanhKhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDTHanhKhach", DbType="VarChar(20)")]
		public string SDTHanhKhach
		{
			get
			{
				return this._SDTHanhKhach;
			}
			set
			{
				if ((this._SDTHanhKhach != value))
				{
					this.OnSDTHanhKhachChanging(value);
					this.SendPropertyChanging();
					this._SDTHanhKhach = value;
					this.SendPropertyChanged("SDTHanhKhach");
					this.OnSDTHanhKhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongMua", DbType="Int")]
		public System.Nullable<int> SoLuongMua
		{
			get
			{
				return this._SoLuongMua;
			}
			set
			{
				if ((this._SoLuongMua != value))
				{
					this.OnSoLuongMuaChanging(value);
					this.SendPropertyChanging();
					this._SoLuongMua = value;
					this.SendPropertyChanged("SoLuongMua");
					this.OnSoLuongMuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaVe", DbType="Int")]
		public System.Nullable<int> GiaVe
		{
			get
			{
				return this._GiaVe;
			}
			set
			{
				if ((this._GiaVe != value))
				{
					this.OnGiaVeChanging(value);
					this.SendPropertyChanging();
					this._GiaVe = value;
					this.SendPropertyChanged("GiaVe");
					this.OnGiaVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Int")]
		public System.Nullable<int> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuyenXe_BanVe", Storage="_ChuyenXe", ThisKey="IdChuyen", OtherKey="IdChuyen", IsForeignKey=true)]
		public ChuyenXe ChuyenXe
		{
			get
			{
				return this._ChuyenXe.Entity;
			}
			set
			{
				ChuyenXe previousValue = this._ChuyenXe.Entity;
				if (((previousValue != value) 
							|| (this._ChuyenXe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChuyenXe.Entity = null;
						previousValue.BanVes.Remove(this);
					}
					this._ChuyenXe.Entity = value;
					if ((value != null))
					{
						value.BanVes.Add(this);
						this._IdChuyen = value.IdChuyen;
					}
					else
					{
						this._IdChuyen = default(string);
					}
					this.SendPropertyChanged("ChuyenXe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietTuyen")]
	public partial class ChiTietTuyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdTuyen;
		
		private string _IdThoiDiem;
		
		private EntityRef<ThoiDiem> _ThoiDiem;
		
		private EntityRef<TuyenXe> _TuyenXe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdTuyenChanging(string value);
    partial void OnIdTuyenChanged();
    partial void OnIdThoiDiemChanging(string value);
    partial void OnIdThoiDiemChanged();
    #endregion
		
		public ChiTietTuyen()
		{
			this._ThoiDiem = default(EntityRef<ThoiDiem>);
			this._TuyenXe = default(EntityRef<TuyenXe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTuyen", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdTuyen
		{
			get
			{
				return this._IdTuyen;
			}
			set
			{
				if ((this._IdTuyen != value))
				{
					if (this._TuyenXe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdTuyenChanging(value);
					this.SendPropertyChanging();
					this._IdTuyen = value;
					this.SendPropertyChanged("IdTuyen");
					this.OnIdTuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdThoiDiem", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdThoiDiem
		{
			get
			{
				return this._IdThoiDiem;
			}
			set
			{
				if ((this._IdThoiDiem != value))
				{
					if (this._ThoiDiem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdThoiDiemChanging(value);
					this.SendPropertyChanging();
					this._IdThoiDiem = value;
					this.SendPropertyChanged("IdThoiDiem");
					this.OnIdThoiDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThoiDiem_ChiTietTuyen", Storage="_ThoiDiem", ThisKey="IdThoiDiem", OtherKey="IdThoiDiem", IsForeignKey=true)]
		public ThoiDiem ThoiDiem
		{
			get
			{
				return this._ThoiDiem.Entity;
			}
			set
			{
				ThoiDiem previousValue = this._ThoiDiem.Entity;
				if (((previousValue != value) 
							|| (this._ThoiDiem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThoiDiem.Entity = null;
						previousValue.ChiTietTuyens.Remove(this);
					}
					this._ThoiDiem.Entity = value;
					if ((value != null))
					{
						value.ChiTietTuyens.Add(this);
						this._IdThoiDiem = value.IdThoiDiem;
					}
					else
					{
						this._IdThoiDiem = default(string);
					}
					this.SendPropertyChanged("ThoiDiem");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TuyenXe_ChiTietTuyen", Storage="_TuyenXe", ThisKey="IdTuyen", OtherKey="IdTuyen", IsForeignKey=true)]
		public TuyenXe TuyenXe
		{
			get
			{
				return this._TuyenXe.Entity;
			}
			set
			{
				TuyenXe previousValue = this._TuyenXe.Entity;
				if (((previousValue != value) 
							|| (this._TuyenXe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TuyenXe.Entity = null;
						previousValue.ChiTietTuyens.Remove(this);
					}
					this._TuyenXe.Entity = value;
					if ((value != null))
					{
						value.ChiTietTuyens.Add(this);
						this._IdTuyen = value.IdTuyen;
					}
					else
					{
						this._IdTuyen = default(string);
					}
					this.SendPropertyChanged("TuyenXe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChuyenXe")]
	public partial class ChuyenXe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdChuyen;
		
		private string _IdTuyen;
		
		private System.Nullable<System.DateTime> _NgayDi;
		
		private string _Gio;
		
		private string _So_Xe;
		
		private EntitySet<BanVe> _BanVes;
		
		private EntityRef<TuyenXe> _TuyenXe;
		
		private EntityRef<Xe> _Xe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChuyenChanging(string value);
    partial void OnIdChuyenChanged();
    partial void OnIdTuyenChanging(string value);
    partial void OnIdTuyenChanged();
    partial void OnNgayDiChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDiChanged();
    partial void OnGioChanging(string value);
    partial void OnGioChanged();
    partial void OnSo_XeChanging(string value);
    partial void OnSo_XeChanged();
    #endregion
		
		public ChuyenXe()
		{
			this._BanVes = new EntitySet<BanVe>(new Action<BanVe>(this.attach_BanVes), new Action<BanVe>(this.detach_BanVes));
			this._TuyenXe = default(EntityRef<TuyenXe>);
			this._Xe = default(EntityRef<Xe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdChuyen", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdChuyen
		{
			get
			{
				return this._IdChuyen;
			}
			set
			{
				if ((this._IdChuyen != value))
				{
					this.OnIdChuyenChanging(value);
					this.SendPropertyChanging();
					this._IdChuyen = value;
					this.SendPropertyChanged("IdChuyen");
					this.OnIdChuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTuyen", DbType="VarChar(30)")]
		public string IdTuyen
		{
			get
			{
				return this._IdTuyen;
			}
			set
			{
				if ((this._IdTuyen != value))
				{
					if (this._TuyenXe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdTuyenChanging(value);
					this.SendPropertyChanging();
					this._IdTuyen = value;
					this.SendPropertyChanged("IdTuyen");
					this.OnIdTuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDi", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDi
		{
			get
			{
				return this._NgayDi;
			}
			set
			{
				if ((this._NgayDi != value))
				{
					this.OnNgayDiChanging(value);
					this.SendPropertyChanging();
					this._NgayDi = value;
					this.SendPropertyChanged("NgayDi");
					this.OnNgayDiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gio", DbType="VarChar(10)")]
		public string Gio
		{
			get
			{
				return this._Gio;
			}
			set
			{
				if ((this._Gio != value))
				{
					this.OnGioChanging(value);
					this.SendPropertyChanging();
					this._Gio = value;
					this.SendPropertyChanged("Gio");
					this.OnGioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_Xe", DbType="VarChar(8)")]
		public string So_Xe
		{
			get
			{
				return this._So_Xe;
			}
			set
			{
				if ((this._So_Xe != value))
				{
					if (this._Xe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSo_XeChanging(value);
					this.SendPropertyChanging();
					this._So_Xe = value;
					this.SendPropertyChanged("So_Xe");
					this.OnSo_XeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuyenXe_BanVe", Storage="_BanVes", ThisKey="IdChuyen", OtherKey="IdChuyen")]
		public EntitySet<BanVe> BanVes
		{
			get
			{
				return this._BanVes;
			}
			set
			{
				this._BanVes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TuyenXe_ChuyenXe", Storage="_TuyenXe", ThisKey="IdTuyen", OtherKey="IdTuyen", IsForeignKey=true)]
		public TuyenXe TuyenXe
		{
			get
			{
				return this._TuyenXe.Entity;
			}
			set
			{
				TuyenXe previousValue = this._TuyenXe.Entity;
				if (((previousValue != value) 
							|| (this._TuyenXe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TuyenXe.Entity = null;
						previousValue.ChuyenXes.Remove(this);
					}
					this._TuyenXe.Entity = value;
					if ((value != null))
					{
						value.ChuyenXes.Add(this);
						this._IdTuyen = value.IdTuyen;
					}
					else
					{
						this._IdTuyen = default(string);
					}
					this.SendPropertyChanged("TuyenXe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Xe_ChuyenXe", Storage="_Xe", ThisKey="So_Xe", OtherKey="So_Xe", IsForeignKey=true)]
		public Xe Xe
		{
			get
			{
				return this._Xe.Entity;
			}
			set
			{
				Xe previousValue = this._Xe.Entity;
				if (((previousValue != value) 
							|| (this._Xe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Xe.Entity = null;
						previousValue.ChuyenXes.Remove(this);
					}
					this._Xe.Entity = value;
					if ((value != null))
					{
						value.ChuyenXes.Add(this);
						this._So_Xe = value.So_Xe;
					}
					else
					{
						this._So_Xe = default(string);
					}
					this.SendPropertyChanged("Xe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BanVes(BanVe entity)
		{
			this.SendPropertyChanging();
			entity.ChuyenXe = this;
		}
		
		private void detach_BanVes(BanVe entity)
		{
			this.SendPropertyChanging();
			entity.ChuyenXe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiNguoiDung")]
	public partial class LoaiNguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdLoaiND;
		
		private string _TenLoaiND;
		
		private EntitySet<NguoiDung> _NguoiDungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdLoaiNDChanging(string value);
    partial void OnIdLoaiNDChanged();
    partial void OnTenLoaiNDChanging(string value);
    partial void OnTenLoaiNDChanged();
    #endregion
		
		public LoaiNguoiDung()
		{
			this._NguoiDungs = new EntitySet<NguoiDung>(new Action<NguoiDung>(this.attach_NguoiDungs), new Action<NguoiDung>(this.detach_NguoiDungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdLoaiND", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdLoaiND
		{
			get
			{
				return this._IdLoaiND;
			}
			set
			{
				if ((this._IdLoaiND != value))
				{
					this.OnIdLoaiNDChanging(value);
					this.SendPropertyChanging();
					this._IdLoaiND = value;
					this.SendPropertyChanged("IdLoaiND");
					this.OnIdLoaiNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiND", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string TenLoaiND
		{
			get
			{
				return this._TenLoaiND;
			}
			set
			{
				if ((this._TenLoaiND != value))
				{
					this.OnTenLoaiNDChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiND = value;
					this.SendPropertyChanged("TenLoaiND");
					this.OnTenLoaiNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiNguoiDung_NguoiDung", Storage="_NguoiDungs", ThisKey="IdLoaiND", OtherKey="IdLoaiND")]
		public EntitySet<NguoiDung> NguoiDungs
		{
			get
			{
				return this._NguoiDungs;
			}
			set
			{
				this._NguoiDungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.LoaiNguoiDung = this;
		}
		
		private void detach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.LoaiNguoiDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDung")]
	public partial class NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdNguoiDung;
		
		private string _PassND;
		
		private string _HoTen;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _GioiTinh;
		
		private string _DiaChi;
		
		private string _SoDT;
		
		private string _IdLoaiND;
		
		private EntityRef<LoaiNguoiDung> _LoaiNguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdNguoiDungChanging(string value);
    partial void OnIdNguoiDungChanged();
    partial void OnPassNDChanging(string value);
    partial void OnPassNDChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoDTChanging(string value);
    partial void OnSoDTChanged();
    partial void OnIdLoaiNDChanging(string value);
    partial void OnIdLoaiNDChanged();
    #endregion
		
		public NguoiDung()
		{
			this._LoaiNguoiDung = default(EntityRef<LoaiNguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdNguoiDung", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdNguoiDung
		{
			get
			{
				return this._IdNguoiDung;
			}
			set
			{
				if ((this._IdNguoiDung != value))
				{
					this.OnIdNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._IdNguoiDung = value;
					this.SendPropertyChanged("IdNguoiDung");
					this.OnIdNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassND", DbType="VarChar(30)")]
		public string PassND
		{
			get
			{
				return this._PassND;
			}
			set
			{
				if ((this._PassND != value))
				{
					this.OnPassNDChanging(value);
					this.SendPropertyChanging();
					this._PassND = value;
					this.SendPropertyChanged("PassND");
					this.OnPassNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(3) NOT NULL", CanBeNull=false)]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDT", DbType="VarChar(15)")]
		public string SoDT
		{
			get
			{
				return this._SoDT;
			}
			set
			{
				if ((this._SoDT != value))
				{
					this.OnSoDTChanging(value);
					this.SendPropertyChanging();
					this._SoDT = value;
					this.SendPropertyChanged("SoDT");
					this.OnSoDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdLoaiND", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string IdLoaiND
		{
			get
			{
				return this._IdLoaiND;
			}
			set
			{
				if ((this._IdLoaiND != value))
				{
					if (this._LoaiNguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdLoaiNDChanging(value);
					this.SendPropertyChanging();
					this._IdLoaiND = value;
					this.SendPropertyChanged("IdLoaiND");
					this.OnIdLoaiNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiNguoiDung_NguoiDung", Storage="_LoaiNguoiDung", ThisKey="IdLoaiND", OtherKey="IdLoaiND", IsForeignKey=true)]
		public LoaiNguoiDung LoaiNguoiDung
		{
			get
			{
				return this._LoaiNguoiDung.Entity;
			}
			set
			{
				LoaiNguoiDung previousValue = this._LoaiNguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._LoaiNguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiNguoiDung.Entity = null;
						previousValue.NguoiDungs.Remove(this);
					}
					this._LoaiNguoiDung.Entity = value;
					if ((value != null))
					{
						value.NguoiDungs.Add(this);
						this._IdLoaiND = value.IdLoaiND;
					}
					else
					{
						this._IdLoaiND = default(string);
					}
					this.SendPropertyChanged("LoaiNguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThoiDiem")]
	public partial class ThoiDiem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdThoiDiem;
		
		private System.DateTime _Ngay;
		
		private string _Gio;
		
		private EntitySet<ChiTietTuyen> _ChiTietTuyens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdThoiDiemChanging(string value);
    partial void OnIdThoiDiemChanged();
    partial void OnNgayChanging(System.DateTime value);
    partial void OnNgayChanged();
    partial void OnGioChanging(string value);
    partial void OnGioChanged();
    #endregion
		
		public ThoiDiem()
		{
			this._ChiTietTuyens = new EntitySet<ChiTietTuyen>(new Action<ChiTietTuyen>(this.attach_ChiTietTuyens), new Action<ChiTietTuyen>(this.detach_ChiTietTuyens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdThoiDiem", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdThoiDiem
		{
			get
			{
				return this._IdThoiDiem;
			}
			set
			{
				if ((this._IdThoiDiem != value))
				{
					this.OnIdThoiDiemChanging(value);
					this.SendPropertyChanging();
					this._IdThoiDiem = value;
					this.SendPropertyChanged("IdThoiDiem");
					this.OnIdThoiDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay", DbType="Date NOT NULL")]
		public System.DateTime Ngay
		{
			get
			{
				return this._Ngay;
			}
			set
			{
				if ((this._Ngay != value))
				{
					this.OnNgayChanging(value);
					this.SendPropertyChanging();
					this._Ngay = value;
					this.SendPropertyChanged("Ngay");
					this.OnNgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gio", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Gio
		{
			get
			{
				return this._Gio;
			}
			set
			{
				if ((this._Gio != value))
				{
					this.OnGioChanging(value);
					this.SendPropertyChanging();
					this._Gio = value;
					this.SendPropertyChanged("Gio");
					this.OnGioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThoiDiem_ChiTietTuyen", Storage="_ChiTietTuyens", ThisKey="IdThoiDiem", OtherKey="IdThoiDiem")]
		public EntitySet<ChiTietTuyen> ChiTietTuyens
		{
			get
			{
				return this._ChiTietTuyens;
			}
			set
			{
				this._ChiTietTuyens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietTuyens(ChiTietTuyen entity)
		{
			this.SendPropertyChanging();
			entity.ThoiDiem = this;
		}
		
		private void detach_ChiTietTuyens(ChiTietTuyen entity)
		{
			this.SendPropertyChanging();
			entity.ThoiDiem = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TuyenXe")]
	public partial class TuyenXe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdTuyen;
		
		private string _TenTuyen;
		
		private string _DiaDiemDi;
		
		private string _DiaDiemDen;
		
		private EntitySet<ChiTietTuyen> _ChiTietTuyens;
		
		private EntitySet<ChuyenXe> _ChuyenXes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdTuyenChanging(string value);
    partial void OnIdTuyenChanged();
    partial void OnTenTuyenChanging(string value);
    partial void OnTenTuyenChanged();
    partial void OnDiaDiemDiChanging(string value);
    partial void OnDiaDiemDiChanged();
    partial void OnDiaDiemDenChanging(string value);
    partial void OnDiaDiemDenChanged();
    #endregion
		
		public TuyenXe()
		{
			this._ChiTietTuyens = new EntitySet<ChiTietTuyen>(new Action<ChiTietTuyen>(this.attach_ChiTietTuyens), new Action<ChiTietTuyen>(this.detach_ChiTietTuyens));
			this._ChuyenXes = new EntitySet<ChuyenXe>(new Action<ChuyenXe>(this.attach_ChuyenXes), new Action<ChuyenXe>(this.detach_ChuyenXes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTuyen", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdTuyen
		{
			get
			{
				return this._IdTuyen;
			}
			set
			{
				if ((this._IdTuyen != value))
				{
					this.OnIdTuyenChanging(value);
					this.SendPropertyChanging();
					this._IdTuyen = value;
					this.SendPropertyChanged("IdTuyen");
					this.OnIdTuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTuyen", DbType="NVarChar(30)")]
		public string TenTuyen
		{
			get
			{
				return this._TenTuyen;
			}
			set
			{
				if ((this._TenTuyen != value))
				{
					this.OnTenTuyenChanging(value);
					this.SendPropertyChanging();
					this._TenTuyen = value;
					this.SendPropertyChanged("TenTuyen");
					this.OnTenTuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiemDi", DbType="NVarChar(30)")]
		public string DiaDiemDi
		{
			get
			{
				return this._DiaDiemDi;
			}
			set
			{
				if ((this._DiaDiemDi != value))
				{
					this.OnDiaDiemDiChanging(value);
					this.SendPropertyChanging();
					this._DiaDiemDi = value;
					this.SendPropertyChanged("DiaDiemDi");
					this.OnDiaDiemDiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiemDen", DbType="NVarChar(30)")]
		public string DiaDiemDen
		{
			get
			{
				return this._DiaDiemDen;
			}
			set
			{
				if ((this._DiaDiemDen != value))
				{
					this.OnDiaDiemDenChanging(value);
					this.SendPropertyChanging();
					this._DiaDiemDen = value;
					this.SendPropertyChanged("DiaDiemDen");
					this.OnDiaDiemDenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TuyenXe_ChiTietTuyen", Storage="_ChiTietTuyens", ThisKey="IdTuyen", OtherKey="IdTuyen")]
		public EntitySet<ChiTietTuyen> ChiTietTuyens
		{
			get
			{
				return this._ChiTietTuyens;
			}
			set
			{
				this._ChiTietTuyens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TuyenXe_ChuyenXe", Storage="_ChuyenXes", ThisKey="IdTuyen", OtherKey="IdTuyen")]
		public EntitySet<ChuyenXe> ChuyenXes
		{
			get
			{
				return this._ChuyenXes;
			}
			set
			{
				this._ChuyenXes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietTuyens(ChiTietTuyen entity)
		{
			this.SendPropertyChanging();
			entity.TuyenXe = this;
		}
		
		private void detach_ChiTietTuyens(ChiTietTuyen entity)
		{
			this.SendPropertyChanging();
			entity.TuyenXe = null;
		}
		
		private void attach_ChuyenXes(ChuyenXe entity)
		{
			this.SendPropertyChanging();
			entity.TuyenXe = this;
		}
		
		private void detach_ChuyenXes(ChuyenXe entity)
		{
			this.SendPropertyChanging();
			entity.TuyenXe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Xe")]
	public partial class Xe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _So_Xe;
		
		private string _Hieu_Xe;
		
		private string _Doi_Xe;
		
		private System.Nullable<int> _So_Cho_Ngoi;
		
		private EntitySet<ChuyenXe> _ChuyenXes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSo_XeChanging(string value);
    partial void OnSo_XeChanged();
    partial void OnHieu_XeChanging(string value);
    partial void OnHieu_XeChanged();
    partial void OnDoi_XeChanging(string value);
    partial void OnDoi_XeChanged();
    partial void OnSo_Cho_NgoiChanging(System.Nullable<int> value);
    partial void OnSo_Cho_NgoiChanged();
    #endregion
		
		public Xe()
		{
			this._ChuyenXes = new EntitySet<ChuyenXe>(new Action<ChuyenXe>(this.attach_ChuyenXes), new Action<ChuyenXe>(this.detach_ChuyenXes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_Xe", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string So_Xe
		{
			get
			{
				return this._So_Xe;
			}
			set
			{
				if ((this._So_Xe != value))
				{
					this.OnSo_XeChanging(value);
					this.SendPropertyChanging();
					this._So_Xe = value;
					this.SendPropertyChanged("So_Xe");
					this.OnSo_XeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hieu_Xe", DbType="VarChar(50)")]
		public string Hieu_Xe
		{
			get
			{
				return this._Hieu_Xe;
			}
			set
			{
				if ((this._Hieu_Xe != value))
				{
					this.OnHieu_XeChanging(value);
					this.SendPropertyChanging();
					this._Hieu_Xe = value;
					this.SendPropertyChanged("Hieu_Xe");
					this.OnHieu_XeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doi_Xe", DbType="VarChar(4)")]
		public string Doi_Xe
		{
			get
			{
				return this._Doi_Xe;
			}
			set
			{
				if ((this._Doi_Xe != value))
				{
					this.OnDoi_XeChanging(value);
					this.SendPropertyChanging();
					this._Doi_Xe = value;
					this.SendPropertyChanged("Doi_Xe");
					this.OnDoi_XeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_Cho_Ngoi", DbType="Int")]
		public System.Nullable<int> So_Cho_Ngoi
		{
			get
			{
				return this._So_Cho_Ngoi;
			}
			set
			{
				if ((this._So_Cho_Ngoi != value))
				{
					this.OnSo_Cho_NgoiChanging(value);
					this.SendPropertyChanging();
					this._So_Cho_Ngoi = value;
					this.SendPropertyChanged("So_Cho_Ngoi");
					this.OnSo_Cho_NgoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Xe_ChuyenXe", Storage="_ChuyenXes", ThisKey="So_Xe", OtherKey="So_Xe")]
		public EntitySet<ChuyenXe> ChuyenXes
		{
			get
			{
				return this._ChuyenXes;
			}
			set
			{
				this._ChuyenXes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChuyenXes(ChuyenXe entity)
		{
			this.SendPropertyChanging();
			entity.Xe = this;
		}
		
		private void detach_ChuyenXes(ChuyenXe entity)
		{
			this.SendPropertyChanging();
			entity.Xe = null;
		}
	}
}
#pragma warning restore 1591
